version: "3.8"

services:
  backend:
    build: ./backend
    container_name: centrale-nantes-backend
    ports:
      - "8000:8000"
    environment:
      - CONSUMER_KEY=your_consumer_key
      - CONSUMER_SECRET=your_consumer_secret
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build: ./frontend
    container_name: centrale-nantes-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8000
    command: npm start
